### ISSUE TITLE
Comments indicate works on ATMega168, no mention of newer processors.

### ISSUE THREAD

**Issue by ofloveandhate** [damellis/PCM#2]
comment in PCM.h indicates the code works on ATMega168.  But newer Arduino such as the [Uno](https://www.adafruit.com/product/50) or the [Pro Mini](https://www.arduino.cc/en/Main/arduinoBoardProMini) use a 328, which appear to have [superceded the 168](https://www.sparkfun.com/products/retired/7957).  

Does this code work with a 328?  [This post using an Uno](http://highlowtech.org/?p=1963) seems to indicate `true`.

**Comment by damellis** [comment]
Yes, this code works with the 328.
